services:
  finnikacc_kv:
    image: redis:latest
    container_name: finnikacc-kv
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis_insight:
    image: "redislabs/redisinsight:latest"
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/data

  finnikacc_api:
    container_name: finnikacc-api
    build:
      context: .
      dockerfile: packages/finnikacc-api/Dockerfile
    volumes:
      - ./:/app  # mount current directory into container
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - APP_ENV=dev_container
  
  finnikacc_ui:
    container_name: finnikacc-ui
    build:
      context: .
      dockerfile: webapps/finnikacc-ui/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./webapps/finnikacc-ui:/app/webapps/finnikacc-ui
    environment:
      VITE_API_SERVER_URL: http://localhost:8000/api-web-app
      NODE_ENV: development


volumes:
  redis_data:
  redis_insight_data:
