services:
  - type: web
    runtime: static
    name: finnikacc-ui
    buildCommand: npm run build -w webapps/finnikacc-ui
    staticPublishPath: webapps/finnikacc-ui/dist
    pullRequestPreviewsEnabled: true
    autoDeployTrigger: off
    domains:
    - cc.finnika.app
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - webapps/finnikacc-ui/**/*
      ignoredPaths:
        - webapps/finnikacc-ui/README.md
        - webapps/finnikacc-ui/src/**/__tests__/*
        - webapps/finnikacc-ui/**/.*

  - type: keyvalue
    name: finnikacc-kv
    ipAllowList: []
    region: frankfurt
    plan: free
    maxmemoryPolicy: allkeys-lru

  - type: web
    name: finnikacc-api
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: uv sync --frozen --no-cache
    startCommand: cd packages/finnikacc-api; uv run uvicorn finnikacc_api.main:app --host 0.0.0.0 --port 8000 --use-colors --no-access-log
    branch: 3-hourly-scheduled-conversion-rates-fetch
    autoDeployTrigger: commit
    healthCheckPath: /status
    domains:
    - api.cc.finnika.app
    buildFilter:
      paths:
        - pyproject.toml
        - uv.lock
        - packages/finnikacc-api/**/*
      ignoredPaths:
        - packages/finnikacc-api/tests/**/*
        - packages/finnikacc-api/Dockerfile
    envVars:
      - fromGroup: finnikacc-eg-secrets
      - key: APP_ENV
        value: prod_render
      - key: REDIS_CONNECTION_STRING
        fromService:
          name: finnikacc-kv
          type: keyvalue
          property: connectionString
