services:
  - type: web
    runtime: static
    name: finnikacc-ui
    buildCommand: npm run build -w webapps/finnikacc-ui
    staticPublishPath: webapps/finnikacc-ui/dist # or public, or whatever your build output directory is
    pullRequestPreviewsEnabled: true
    autoDeployTrigger: off
    domains:
    - cc.finnika.app
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - webapps/finnikacc-ui/**/*
      ignoredPaths:
        - webapps/finnikacc-ui/README.md
        - webapps/finnikacc-ui/src/**/__tests__/*
        - webapps/finnikacc-ui/**/.*
    # envVars:
    #   - key: VUE_APP_API_URL
    #     value: https://api.example.com