name: Deploy to Render

on:
  workflow_call:
    inputs:
      commit_sha:
        required: true
        type: string
    secrets:
        RENDER_API_KEY:
            required: true
        RENDER_SERVICE_ID:
            required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render API deploy
        run: |
          curl --fail -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{\"commitId\": \"${{ inputs.commit_sha }}\"}" \
            "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys"
