name: Deploy UI to Render

on:
  push:
    tags:
      - 'prod-ui-*'

jobs:
  deploy-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render UI deploy
        run: |
          curl --fail -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{\"commitId\": \"${{ github.sha }}\"}" \
            https://api.render.com/v1/services/${{ secrets.RENDER_CC_UI_SERVICE_ID }}/deploys
